Traceback (most recent call last):
  File "/home/inma/anaconda3/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/inma/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/inma/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/inma/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/home/inma/anaconda3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/inma/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 540, in async_execute
    await self.async_execute_cell(
  File "/home/inma/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/inma/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# PENALIZED B-SPLINES IN PYGAM
gam_pbs = LinearGAM(s(0),s(1),s(2),s(3))
gam_pbs.gridsearch(X.reshape(-1,1),y)
yy_pred_pbs = gam_pbs.predict(X.reshape(-1,1))
plt.figure(figsize=(8,5))
plt.plot(X,y, 'o')
#plt.plot(xx,ffun(xx), color="red", LineWidth=3)
plt.plot(X,yy_pred_pbs, color='red', LineWidth=2)
plt.legend(["Observed", "Ground Truth", "Prediction"])
plt.show()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
[0;32m~/anaconda3/lib/python3.8/site-packages/pygam/utils.py[0m in [0;36mcheck_param[0;34m(param, param_name, dtype, constraint, iterable, max_depth)[0m
[1;32m    378[0m     [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 379[0;31m         [0mparam_dt[0m [0;34m=[0m [0mnp[0m[0;34m.[0m[0marray[0m[0;34m([0m[0mflatten[0m[0;34m([0m[0mparam[0m[0;34m)[0m[0;34m)[0m[0;31m# + np.zeros_like(flatten(param), dtype='int')[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    380[0m         [0;31m# param_dt = np.array(param).astype(dtype)[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/anaconda3/lib/python3.8/site-packages/pygam/utils.py[0m in [0;36mflatten[0;34m(iterable)[0m
[1;32m    822[0m         [0mflat[0m [0;34m=[0m [0;34m[[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 823[0;31m         [0;32mfor[0m [0mitem[0m [0;32min[0m [0mlist[0m[0;34m([0m[0miterable[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    824[0m             [0mitem[0m [0;34m=[0m [0mflatten[0m[0;34m([0m[0mitem[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mTypeError[0m: 'SplineTerm' object is not iterable

During handling of the above exception, another exception occurred:

[0;31mTypeError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-9-00bdaed1ce60>[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0;31m# PENALIZED B-SPLINES IN PYGAM[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m      2[0m [0mgam_pbs[0m [0;34m=[0m [0mLinearGAM[0m[0;34m([0m[0ms[0m[0;34m([0m[0;36m0[0m[0;34m)[0m[0;34m,[0m[0ms[0m[0;34m([0m[0;36m1[0m[0;34m)[0m[0;34m,[0m[0ms[0m[0;34m([0m[0;36m2[0m[0;34m)[0m[0;34m,[0m[0ms[0m[0;34m([0m[0;36m3[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 3[0;31m [0mgam_pbs[0m[0;34m.[0m[0mgridsearch[0m[0;34m([0m[0mX[0m[0;34m.[0m[0mreshape[0m[0;34m([0m[0;34m-[0m[0;36m1[0m[0;34m,[0m[0;36m1[0m[0;34m)[0m[0;34m,[0m[0my[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      4[0m [0myy_pred_pbs[0m [0;34m=[0m [0mgam_pbs[0m[0;34m.[0m[0mpredict[0m[0;34m([0m[0mX[0m[0;34m.[0m[0mreshape[0m[0;34m([0m[0;34m-[0m[0;36m1[0m[0;34m,[0m[0;36m1[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m [0mplt[0m[0;34m.[0m[0mfigure[0m[0;34m([0m[0mfigsize[0m[0;34m=[0m[0;34m([0m[0;36m8[0m[0;34m,[0m[0;36m5[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/anaconda3/lib/python3.8/site-packages/pygam/pygam.py[0m in [0;36mgridsearch[0;34m(self, X, y, weights, return_scores, keep_best, objective, progress, **param_grids)[0m
[1;32m   1770[0m         [0;31m# check if model fitted[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1771[0m         [0;32mif[0m [0;32mnot[0m [0mself[0m[0;34m.[0m[0m_is_fitted[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1772[0;31m             [0mself[0m[0;34m.[0m[0m_validate_params[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1773[0m             [0mself[0m[0;34m.[0m[0m_validate_data_dep_params[0m[0;34m([0m[0mX[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1774[0m [0;34m[0m[0m

[0;32m~/anaconda3/lib/python3.8/site-packages/pygam/pygam.py[0m in [0;36m_validate_params[0;34m(self)[0m
[1;32m   2284[0m         """
[1;32m   2285[0m         [0mself[0m[0;34m.[0m[0mdistribution[0m [0;34m=[0m [0mNormalDist[0m[0;34m([0m[0mscale[0m[0;34m=[0m[0mself[0m[0;34m.[0m[0mscale[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 2286[0;31m         [0msuper[0m[0;34m([0m[0mLinearGAM[0m[0;34m,[0m [0mself[0m[0;34m)[0m[0;34m.[0m[0m_validate_params[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   2287[0m [0;34m[0m[0m
[1;32m   2288[0m     [0;32mdef[0m [0mprediction_intervals[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mX[0m[0;34m,[0m [0mwidth[0m[0;34m=[0m[0;36m.95[0m[0;34m,[0m [0mquantiles[0m[0;34m=[0m[0;32mNone[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/anaconda3/lib/python3.8/site-packages/pygam/pygam.py[0m in [0;36m_validate_params[0;34m(self)[0m
[1;32m    228[0m [0;34m[0m[0m
[1;32m    229[0m         [0;31m# max_iter[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 230[0;31m         self.max_iter = check_param(self.max_iter, param_name='max_iter',
[0m[1;32m    231[0m                                     [0mdtype[0m[0;34m=[0m[0;34m'int'[0m[0;34m,[0m [0mconstraint[0m[0;34m=[0m[0;34m'>=1'[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m    232[0m                                     iterable=False)

[0;32m~/anaconda3/lib/python3.8/site-packages/pygam/utils.py[0m in [0;36mcheck_param[0;34m(param, param_name, dtype, constraint, iterable, max_depth)[0m
[1;32m    380[0m         [0;31m# param_dt = np.array(param).astype(dtype)[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m    381[0m     [0;32mexcept[0m [0;34m([0m[0mValueError[0m[0;34m,[0m [0mTypeError[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 382[0;31m         [0;32mraise[0m [0mTypeError[0m[0;34m([0m[0mmsg[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    383[0m [0;34m[0m[0m
[1;32m    384[0m     [0;31m# check iterable[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m

[0;31mTypeError[0m: max_iter must be int >=1, but found max_iter = s(1)
TypeError: max_iter must be int >=1, but found max_iter = s(1)

