Traceback (most recent call last):
  File "/home/inma/anaconda3/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/inma/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/inma/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/inma/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/home/inma/anaconda3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/inma/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 540, in async_execute
    await self.async_execute_cell(
  File "/home/inma/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/inma/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
gam = LogisticGAM(s(0)+ s(1)+s(2)+ s(3)).gridsearch(X, y)


gam.summary()


print("----------------------------------------------------------------------------------------")
print("GRAFICAS DE DEPENDENCIA PARCIAL")

fig, axs = plt.subplots(1, 4, figsize=(15,6))
titles = ['Distancia_NEW','Landsize','Lattitude','Longtitude']

for i, ax in enumerate(axs):
    XX = gam.generate_X_grid(term=i)
    pdep, confi = gam.partial_dependence(term=i, width=.95)

    ax.plot(XX[:, i], pdep)
    ax.plot(XX[:, i], confi, c='r', ls='--')
    ax.set_title(titles[i]);



------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-5-4b853e2d3f9c>[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0mgam[0m [0;34m=[0m [0mLogisticGAM[0m[0;34m([0m[0ms[0m[0;34m([0m[0;36m0[0m[0;34m)[0m[0;34m+[0m [0ms[0m[0;34m([0m[0;36m1[0m[0;34m)[0m[0;34m+[0m[0ms[0m[0;34m([0m[0;36m2[0m[0;34m)[0m[0;34m+[0m [0ms[0m[0;34m([0m[0;36m3[0m[0;34m)[0m[0;34m)[0m[0;34m.[0m[0mgridsearch[0m[0;34m([0m[0mX[0m[0;34m,[0m [0my[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      2[0m [0;34m[0m[0m
[1;32m      3[0m [0;34m[0m[0m
[1;32m      4[0m [0mgam[0m[0;34m.[0m[0msummary[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m [0;34m[0m[0m

[0;31mNameError[0m: name 'LogisticGAM' is not defined
NameError: name 'LogisticGAM' is not defined

